-- Generated from docs/taste_taxonomy_v1.json (contract: taste_map_v1)
INSERT INTO public.taste_taxonomy (
    code,
    group_code,
    display_name,
    allowed_polarity,
    description,
    version,
    is_active,
    sort_order
)
VALUES
    ('fruity_berry', 'flavor_family', 'Фруктово-ягодный', ARRAY['positive', 'negative']::text[], 'ягоды, косточковые фрукты, джемовые ноты', '2026-03-05', TRUE, 1),
    ('citrus', 'flavor_family', 'Цитрусовый', ARRAY['positive', 'negative']::text[], 'лимон, апельсин, грейпфрут', '2026-03-05', TRUE, 2),
    ('floral', 'flavor_family', 'Цветочный', ARRAY['positive', 'negative']::text[], 'жасмин, цветочный аромат', '2026-03-05', TRUE, 3),
    ('nutty_cocoa', 'flavor_family', 'Орехово-шоколадный', ARRAY['positive', 'negative']::text[], 'фундук, какао, молочный шоколад', '2026-03-05', TRUE, 4),
    ('caramel_sweet', 'flavor_family', 'Карамельно-сладкий', ARRAY['positive', 'negative']::text[], 'карамель, ирис, тростниковый сахар', '2026-03-05', TRUE, 5),
    ('spicy', 'flavor_family', 'Пряный', ARRAY['positive', 'negative']::text[], 'корица, специи', '2026-03-05', TRUE, 6),
    ('roasted_bitter', 'flavor_family', 'Обжарочно-горький', ARRAY['positive', 'negative']::text[], 'темная обжарка, какао-нибс, выраженная горечь', '2026-03-05', TRUE, 7),
    ('herbal_green', 'flavor_family', 'Травянистый', ARRAY['positive', 'negative']::text[], 'зелень, чайные ноты', '2026-03-05', TRUE, 8),
    ('acidity_high', 'structure', 'Яркая кислотность', ARRAY['positive', 'negative']::text[], 'кислотность как заметная и доминирующая часть чашки', '2026-03-05', TRUE, 9),
    ('acidity_low', 'structure', 'Низкая кислотность', ARRAY['positive', 'negative']::text[], 'мягкая кислотность', '2026-03-05', TRUE, 10),
    ('sweetness_high', 'structure', 'Высокая сладость', ARRAY['positive', 'negative']::text[], 'ощутимая природная сладость', '2026-03-05', TRUE, 11),
    ('bitterness_high', 'structure', 'Высокая горечь', ARRAY['positive', 'negative']::text[], 'заметная горечь', '2026-03-05', TRUE, 12),
    ('body_light', 'structure', 'Легкое тело', ARRAY['positive', 'negative']::text[], 'чайное, легкое ощущение плотности', '2026-03-05', TRUE, 13),
    ('body_heavy', 'structure', 'Плотное тело', ARRAY['positive', 'negative']::text[], 'сиропистость, насыщенная плотность', '2026-03-05', TRUE, 14),
    ('aftertaste_long', 'structure', 'Долгое послевкусие', ARRAY['positive', 'negative']::text[], 'длительное послевкусие', '2026-03-05', TRUE, 15),
    ('aftertaste_short', 'structure', 'Короткое послевкусие', ARRAY['positive', 'negative']::text[], 'короткое, быстро исчезающее послевкусие', '2026-03-05', TRUE, 16),
    ('espresso', 'brew_preference', 'Эспрессо', ARRAY['positive']::text[], 'предпочитает эспрессо-подачу', '2026-03-05', TRUE, 17),
    ('milk_based', 'brew_preference', 'Молочные напитки', ARRAY['positive']::text[], 'предпочитает капучино/латте и аналогичные', '2026-03-05', TRUE, 18),
    ('filter', 'brew_preference', 'Фильтр', ARRAY['positive']::text[], 'предпочитает filter/alternative brew', '2026-03-05', TRUE, 19),
    ('cold', 'brew_preference', 'Холодные кофейные напитки', ARRAY['positive']::text[], 'предпочитает cold brew/iced форматы', '2026-03-05', TRUE, 20),
    ('black_only', 'milk_preference', 'Черный кофе', ARRAY['positive']::text[], 'обычно без молока', '2026-03-05', TRUE, 21),
    ('milk_ok', 'milk_preference', 'С молоком', ARRAY['positive']::text[], 'обычно с молоком', '2026-03-05', TRUE, 22),
    ('plant_milk_preferred', 'milk_preference', 'Растительное молоко', ARRAY['positive']::text[], 'предпочтение растительного молока', '2026-03-05', TRUE, 23),
    ('hot', 'serving', 'Горячая подача', ARRAY['positive']::text[], 'предпочтение горячих напитков', '2026-03-05', TRUE, 24),
    ('iced', 'serving', 'Холодная подача', ARRAY['positive']::text[], 'предпочтение холодной подачи', '2026-03-05', TRUE, 25),
    ('quick_pickup', 'context', 'Быстро взять с собой', ARRAY['positive']::text[], 'сценарий to-go и скорость', '2026-03-05', TRUE, 26),
    ('work_focus', 'context', 'Для работы', ARRAY['positive']::text[], 'важен спокойный рабочий сценарий', '2026-03-05', TRUE, 27),
    ('slow_weekend', 'context', 'Медленный выходной', ARRAY['positive']::text[], 'сценарий неспешного визита', '2026-03-05', TRUE, 28)
ON CONFLICT (code) DO UPDATE SET
    group_code = EXCLUDED.group_code,
    display_name = EXCLUDED.display_name,
    allowed_polarity = EXCLUDED.allowed_polarity,
    description = EXCLUDED.description,
    version = EXCLUDED.version,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();
